Panaceya/Controllers/Medicines1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Panaceya.Models;

namespace Panaceya.Controllers
{
    public class Medicines1Controller : Controller
    {
        private my_panaceyaEntities db = new my_panaceyaEntities();

        // GET: Medicines1
        public ActionResult Index()
        {
            var medicines = db.Medicines.Include(m => m.Categories);
            return View(medicines.ToList());
        } 
        public ActionResult ElementesMedicines(string id)
        {
            int idCat = Convert.ToInt32(id);
            var medicines = db.Medicines.Include(m => m.Categories).Where(e => e.ID_Category == idCat);
            return PartialView(medicines.ToList());
        }

        // GET: Medicines1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicines medicines = db.Medicines.Find(id);
            if (medicines == null)
            {
                return HttpNotFound();
            }
            return View(medicines);
        }

        // GET: Medicines1/Create
        public ActionResult Create()
        {
            ViewBag.ID_Category = new SelectList(db.Categories, "ID_Category", "Name");
            return View();
        }

        // POST: Medicines1/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Medicines medicines, HttpPostedFileBase Pic)
        {
            if (ModelState.IsValid)
            {
                string fileName = null;
                if (Pic != null)
                {
                    fileName = Path.GetFileName(Pic.FileName);
                    string extensionImage = getFileExtension(fileName);
                    fileName = Guid.NewGuid() + "." + extensionImage;
                    var path = Path.Combine(Server.MapPath("~/Content/Images"), fileName);
                    Pic.SaveAs(path);
                }
                medicines.Photo = fileName;
                db.Medicines.Add(medicines);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_Category = new SelectList(db.Categories, "ID_Category", "Name", medicines.ID_Category);
            return View(medicines);
        }

        // GET: Medicines1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicines medicines = db.Medicines.Find(id);
            if (medicines == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Category = new SelectList(db.Categories, "ID_Category", "Name", medicines.ID_Category);
            return View(medicines);
        }

        // POST: Medicines1/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Medicine,ID_Category,Name,Description,Price,Amount,Presence,Photo")] Medicines medicines, HttpPostedFileBase Pic)
        {
            if (ModelState.IsValid)
            {
                if (Pic != null)
                {
                    string fileName = null;
                    fileName = Path.GetFileName(Pic.FileName);
                    string extensionImage = getFileExtension(fileName);
                    fileName = Guid.NewGuid() + "." + extensionImage;
                    var path = Path.Combine(Server.MapPath("~/Content/Images"), fileName);
                    Pic.SaveAs(path);
                    medicines.Photo = fileName;
                }
                db.Entry(medicines).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Category = new SelectList(db.Categories, "ID_Category", "Name", medicines.ID_Category);
            return View(medicines);
        }

        // GET: Medicines1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicines medicines = db.Medicines.Find(id);
            if (medicines == null)
            {
                return HttpNotFound();
            }
            return View(medicines);
        }

        // POST: Medicines1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Medicines medicines = db.Medicines.Find(id);
            db.Medicines.Remove(medicines);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public string getFileExtension(string fileName) // Получение типа фотографии
        {
            return fileName.Substring(fileName.LastIndexOf(".") + 1);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Panaceya/Views/Medicines1/Create.cshtml
@model Panaceya.Models.Medicines


@{
    ViewBag.Title = "Create";
}

<h2>Создать новый товар</h2>


@using (Html.BeginForm("Create", "Medicines1", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@

        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Название", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_Category, "Категория", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Category", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, "Описание", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, "Цена", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, "Количество", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Presence, "Наличие", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Presence)
                    @Html.ValidationMessageFor(model => model.Presence, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Photo, "Изображение", htmlAttributes: new { @class = "control-label col-md-2" })
            @*<div class="col-md-10">*@
                <input id="ForPhoto" type="file" name="Pic" accept="image/jpeg,image/png"/>
                @*@Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control", type = "file", name = "Pic" } })
                @Html.ValidationMessageFor(model => model.Presence, "", new { @class = "text-danger" })*@
            @*</div>*@
        </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}



<div>
    @Html.ActionLink("Назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Panaceya/Views/Medicines1/Delete.cshtml
@model Panaceya.Models.Medicines

@{
    ViewBag.Title = "Delete";
}

<h2>Удалить</h2>

<h3>Вы действительно хотите удалить это лекарство?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt class="paragraph">
            Навзание
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="paragraph">
            Описание
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt class="paragraph">
            Цена
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt class="paragraph">
            Количество
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt class="paragraph">
            Наличие
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Presence)
        </dd>

        <dt class="paragraph">
            Категория
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categories.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад", "Index")
        </div>
    }
</div>

Panaceya/Views/Medicines1/Details.cshtml
@model Panaceya.Models.Medicines

@{
    ViewBag.Title = "Details";
}

<h2>Информация</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt class="paragraph">
            Название
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="paragraph">
            Описание
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt class="paragraph">
            Цена
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt class="paragraph">
            Количество
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt class="paragraph">
            Наличие
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Presence)
        </dd>

        <dt class="paragraph">
            Категория
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categories.Name)
        </dd>

        <dt class="paragraph">
            Изображение
        </dt>

        <dd>
            <img src="~/Content/Images/@Html.DisplayFor(model => model.Photo)" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Изменить", "Edit", new { id = Model.ID_Medicine }) |
    @Html.ActionLink("Назад", "Index")
</p>

Panaceya/Views/Medicines1/Edit.cshtml
@model Panaceya.Models.Medicines

@{
    ViewBag.Title = "Edit";
}

<h2>Редактировать</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Medicine)

        <div class="form-group">
            @Html.LabelFor(model => model.Categories, "Категории", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Category", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Categories, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Название", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, "Описание", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, "Цена", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, "Количество", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Presence, "Наличие", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Presence)
                    @Html.ValidationMessageFor(model => model.Presence, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, "Изображение", htmlAttributes: new { @class = "control-label col-md-2" })
            @*<div class="col-md-10">*@
            <input id="ForPhoto" type="file" name="Pic" accept="image/jpeg,image/png" />
            @*@Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control", type = "file", name = "Pic" } })
                @Html.ValidationMessageFor(model => model.Presence, "", new { @class = "text-danger" })*@
            @*</div>*@
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Panaceya/Views/Medicines1/Index.cshtml
@model IEnumerable<Panaceya.Models.Medicines>

@{
    ViewBag.Title = "Index";
}



<h2>Лекарства</h2>

@*<p>
        @Html.ActionLink("Добавить", "Create")
    </p>*@

<table class="table">
    <tr class="paragraph">
        <th>
            Название
        </th>
        @*<th>
            Описание
        </th>*@
        <th>
            Цена
        </th>
        <th >
            Количество
        </th>
        <th>
            Наличие
        </th>
        <th>
            Категория
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td class="center">
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.Presence)*@
                @if (item.Presence == true)
                {
                    <p> В наличии</p>
                }
                else
                {
                    <p>Не наличии</p>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categories.Name)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.ID_Medicine }, new { @class = "lox" }) |
                @Html.ActionLink("Информация", "Details", new { id = item.ID_Medicine }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.ID_Medicine })
            </td>
        </tr>
    }

</table>
<button class="go" onclick="location.href = '/Medicines1/Create';">Добавить товар &raquo;</button>